# Rename/copy this file as config.yml and edit as necessary

# General settings
SECRET_KEY: secret key # Flask application secret key

TRUSTED_PROXIES:

IP_WHITELIST: # Leave blank for access to all

# File management
4CAT_DATASETS_PATH:  # Grant DMI Service Manager direct access to a local 4CAT instance's files

UPLOAD_FOLDER_PATH:  # Path to allow remote endpoints to upload/download files

ALLOWED_EXTENSIONS: # extensions allowed to be uploaded
  - png
  - jpg
  - jpeg
  - gif
  - csv
  - wav
  - mp4
  - mp3
  - json

# Enable GPU support
GPU_ENABLED: True

# Set up Docker endpoints; these images must be available locally (use Docker to pull and tag as necessary)
DOCKER_ENDPOINTS:
  whisper:  # https://github.com/digitalmethodsinitiative/dmi_dockerized_services/
    image_name: whisper
    local: True  # Set to True if 4CAT is running locally
    remote: False  # Set to True if 4CAT is running remotely
    command: whisper
    data_path: /app/data/
  clip:  # https://github.com/digitalmethodsinitiative/dmi_dockerized_services/
    image_name: clip
    local: True
    remote: False
    command: python3 clip_interface.py
    data_path: /app/data/
  pixplot:  # https://github.com/digitalmethodsinitiative/dmi_pix_plot
    image_name: pix_plot_test
    local: True
    remote: False
    command: python /app/pixplot/pixplot.py
    data_path: /app/data/
  ocr:  # https://github.com/digitalmethodsinitiative/ocr_server
    image_name: ocr_server
    local: True
    remote: False
    command: python cli_interface.py
    data_path: /app/data/
  stable_diffusion:  # https://github.com/digitalmethodsinitiative/dmi_dockerized_services/
    image_name: stable_diffusion
    local: True
    remote: False
    command: python interface.py
    data_path: /app/data