# Rename/copy this file as config.yml and edit as necessary

SECRET_KEY: secret key

4CAT_DATASETS_PATH: # 4CAT datasets directory must be accessible to dmi_service_manager for services to access necessary files

TRUSTED_PROXIES: # Be sure to include Docker proxy (e.g., 172.17.0.1 )
#  - 172.17.0.1

IP_WHITELIST: # Leave blank for access to all
#  - 172.17.0.1 # Docker proxy to allow on machine with Docker container
#  - 172.17.0.2 # "Docker, this is Docker speaking"


# Whisper settings
WHISPER_LIVE: False