# Rename/copy this file as config.yml and edit as necessary

# General settings
SECRET_KEY: secret key # Flask application secret key

TRUSTED_PROXIES:

IP_WHITELIST: # Leave blank for access to all

# File management
UPLOAD_FOLDER_PATH:

ALLOWED_EXTENSIONS: # extensions allowed to be uploaded
  - png
  - jpg
  - jpeg
  - gif
  - csv
  - wav
  - mp4
  - mp3


# Grant DMI Service Manager direct access to a 4CAT instance files
4CAT_DATASETS_PATH:

GPU_ENABLED: True